Upgrade Typescript dependency to fix error TS1005
When building the Johnny Fives types, we get the error:

```
node_modules/@types/johnny-five/index.d.ts:663:21 - error TS1005: ',' expected.
663     song: [frequency: string | null, duration: number][];
```

Upgrading to Typescript 4.x solves this issue.